import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Badge, Button, Card, EmptyState, FieldError, FormLabel, PageHeader, SelectInput, TextInput } from '@/Components/shared/ui';
import { Department, Entity, Paginated, rows } from '@/lib/recruitment';
import { Head, router, useForm } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

export default function DepartmentsIndex({ departments, entities }: { departments: Paginated<Department>; entities: Entity[] }): JSX.Element {
    const [editing, setEditing] = useState<Department | null>(null);
    const [open, setOpen] = useState(false);
    const form = useForm({ name: '', entity_id: '', is_active: true as boolean });
    function start(department?: Department): void { setEditing(department ?? null); form.setData({ name: department?.name ?? '', entity_id: String(department?.entity_id ?? ''), is_active: department?.is_active ?? true }); setOpen(true); }
    function submit(event: FormEvent): void { event.preventDefault(); const payload = { ...form.data, entity_id: Number(form.data.entity_id) }; editing ? router.put(`/admin/departments/${editing.id}`, payload, { onSuccess: () => setOpen(false) }) : router.post('/admin/departments', payload, { onSuccess: () => setOpen(false) }); }
    return <AuthenticatedLayout header={<h1 className="text-lg font-semibold">Departemen</h1>}><Head title="Departemen" /><PageHeader title="Departemen" description="Kelola departemen per entitas." actions={<Button onClick={() => start()}>Tambah Departemen</Button>} /><Card className="overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-4">Nama</th><th className="p-4">Entitas</th><th className="p-4">Status</th><th className="p-4 text-right">Aksi</th></tr></thead><tbody className="divide-y">{rows(departments).map((department) => <tr key={department.id}><td className="p-4 font-medium">{department.name}</td><td className="p-4">{department.entity?.name ?? '-'}</td><td className="p-4"><Badge tone={department.is_active ? 'green' : 'slate'}>{department.is_active ? 'Aktif' : 'Nonaktif'}</Badge></td><td className="space-x-2 p-4 text-right"><Button variant="secondary" onClick={() => start(department)}>Edit</Button><Button variant="ghost" onClick={() => confirm('Yakin ubah status departemen?') && router.put(`/admin/departments/${department.id}`, { is_active: !department.is_active }, {})}>Toggle Aktif</Button></td></tr>)}</tbody></table>{rows(departments).length === 0 && <div className="p-4"><EmptyState title="Belum ada departemen" /></div>}</Card>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><Card className="w-full max-w-lg p-6"><h2 className="mb-4 text-lg font-semibold">{editing ? 'Edit Departemen' : 'Tambah Departemen'}</h2><form onSubmit={submit} className="space-y-4"><div><FormLabel>Nama</FormLabel><TextInput value={form.data.name} onChange={(event) => form.setData('name', event.target.value)} /><FieldError message={form.errors.name} /></div><div><FormLabel>Entitas</FormLabel><SelectInput value={form.data.entity_id} onChange={(event) => form.setData('entity_id', event.target.value)}><option value="">Pilih entitas</option>{entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</SelectInput><FieldError message={form.errors.entity_id} /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.is_active} onChange={(event) => form.setData('is_active', event.target.checked)} /> Status aktif</label><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Batal</Button><Button disabled={form.processing}>Simpan</Button></div></form></Card></div>}</AuthenticatedLayout>;
}
