import { Button, Card, FieldError, FormLabel, PageHeader, TextArea } from '@/Components/shared/ui';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { ApplicationItem } from '@/lib/recruitment';
import { Head, Link, useForm } from '@inertiajs/react';

interface BackgroundCheckData { ktp_verified: boolean; ijazah_verified: boolean; certificate_verified: boolean; reference_verified: boolean; notes: string; decision: 'clear' | 'issue' | 'failed'; rejection_reason: string; }

export default function BackgroundCheck({ application }: { application: ApplicationItem }): JSX.Element {
    const current = application.background_check;
    const form = useForm<BackgroundCheckData>({ ktp_verified: false, ijazah_verified: false, certificate_verified: false, reference_verified: false, notes: '', decision: (current?.decision as BackgroundCheckData['decision']) ?? 'clear', rejection_reason: '' });
    function submit(event: React.FormEvent): void { event.preventDefault(); current?.id ? form.put(`/hr/background-check/${application.id}`) : form.post(`/hr/background-check/${application.id}`); }
    return <AuthenticatedLayout header={<h1 className="text-lg font-semibold">Background Check</h1>}><Head title="Background Check" /><PageHeader title="Background Check" description={`${application.candidate?.name ?? 'Kandidat'} - ${application.job_posting?.position_name ?? ''}`} actions={<Link className="text-sm text-blue-600" href="/pipeline">Kembali</Link>} /><Card className="p-6"><form onSubmit={submit} className="space-y-5">{[['ktp_verified','KTP'],['ijazah_verified','Ijazah'],['certificate_verified','Sertifikat'],['reference_verified','Referensi/Pengalaman Kerja (opsional)']].map(([key,label]) => <label key={key} className="flex items-center gap-3 rounded-md border border-slate-200 p-3 text-sm font-medium text-slate-700"><input type="checkbox" checked={Boolean(form.data[key as keyof BackgroundCheckData])} onChange={(event) => form.setData(key as keyof BackgroundCheckData, event.target.checked as never)} />{label}</label>)}<div><FormLabel>Notes</FormLabel><TextArea rows={3} value={form.data.notes} onChange={(event) => form.setData('notes', event.target.value)} /><FieldError message={form.errors.notes} /></div><div><FormLabel>Keputusan</FormLabel><div className="flex flex-wrap gap-3 text-sm">{[['clear','Clear'],['issue','Issue'],['failed','Gagal']].map(([value,label]) => <label key={value} className="flex items-center gap-2"><input type="radio" checked={form.data.decision === value} onChange={() => form.setData('decision', value as BackgroundCheckData['decision'])} />{label}</label>)}</div><FieldError message={form.errors.decision} /></div>{form.data.decision === 'failed' && <div><FormLabel>Alasan Gagal</FormLabel><TextArea rows={3} value={form.data.rejection_reason} onChange={(event) => form.setData('rejection_reason', event.target.value)} /><FieldError message={form.errors.rejection_reason} /></div>}<Button type="submit" disabled={form.processing}>{form.processing ? 'Menyimpan...' : 'Simpan'}</Button></form></Card></AuthenticatedLayout>;
}
