import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Badge, Button, Card, EmptyState, FormLabel, PageHeader, SelectInput } from '@/Components/shared/ui';
import { BasicUser, Entity, Paginated, rows } from '@/lib/recruitment';
import { Head, router, useForm } from '@inertiajs/react';
import { FormEvent, useState } from 'react';
interface Signer { id: number; entity_id: number; user_id: number; document_type: string; is_active: boolean; entity?: Entity; user?: BasicUser }
export default function CompanySignersIndex({ companySigners, entities, users }: { companySigners: Paginated<Signer>; entities: Entity[]; users: BasicUser[] }): JSX.Element {
    const [editing, setEditing] = useState<Signer | null>(null); const [open, setOpen] = useState(false); const form = useForm({ entity_id: '', user_id: '', document_type: 'offering', is_active: true as boolean });
    function start(item?: Signer): void { setEditing(item ?? null); form.setData({ entity_id: String(item?.entity_id ?? ''), user_id: String(item?.user_id ?? ''), document_type: item?.document_type ?? 'offering', is_active: item?.is_active ?? true }); setOpen(true); }
    function submit(event: FormEvent): void { event.preventDefault(); const payload = { ...form.data, entity_id: Number(form.data.entity_id), user_id: Number(form.data.user_id) }; editing ? router.put(`/admin/company-signers/${editing.id}`, payload, { onSuccess: () => setOpen(false) }) : router.post('/admin/company-signers', payload, { onSuccess: () => setOpen(false) }); }
    return <AuthenticatedLayout header={<h1 className="text-lg font-semibold">Company Signer</h1>}><Head title="Company Signer" /><PageHeader title="Company Signer" description="Kelola penanda tangan dokumen Offering dan PKWT." actions={<Button onClick={() => start()}>Tambah Signer</Button>} /><Card className="overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><th className="p-4">Entitas</th><th className="p-4">User</th><th className="p-4">Jenis Dokumen</th><th className="p-4">Status</th><th className="p-4 text-right">Aksi</th></tr></thead><tbody className="divide-y">{rows(companySigners).map((item) => <tr key={item.id}><td className="p-4">{item.entity?.name ?? '-'}</td><td className="p-4">{item.user?.name ?? '-'}</td><td className="p-4"><Badge tone="blue">{item.document_type.toUpperCase()}</Badge></td><td className="p-4"><Badge tone={item.is_active ? 'green' : 'slate'}>{item.is_active ? 'Aktif' : 'Nonaktif'}</Badge></td><td className="space-x-2 p-4 text-right"><Button variant="secondary" onClick={() => start(item)}>Edit</Button><Button variant="ghost" onClick={() => confirm('Yakin ubah status signer?') && router.put(`/admin/company-signers/${item.id}`, { is_active: !item.is_active }, {})}>Toggle Aktif</Button></td></tr>)}</tbody></table>{rows(companySigners).length === 0 && <div className="p-4"><EmptyState title="Belum ada company signer" /></div>}</Card>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><Card className="w-full max-w-lg p-6"><h2 className="mb-4 text-lg font-semibold">{editing ? 'Edit Signer' : 'Tambah Signer'}</h2><form onSubmit={submit} className="space-y-4"><div><FormLabel>Entitas</FormLabel><SelectInput value={form.data.entity_id} onChange={(event) => form.setData('entity_id', event.target.value)}><option value="">Pilih entitas</option>{entities.map((entity) => <option key={entity.id} value={entity.id}>{entity.name}</option>)}</SelectInput></div><div><FormLabel>User</FormLabel><SelectInput value={form.data.user_id} onChange={(event) => form.setData('user_id', event.target.value)}><option value="">Pilih user</option>{users.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</SelectInput></div><div><FormLabel>Jenis Dokumen</FormLabel><SelectInput value={form.data.document_type} onChange={(event) => form.setData('document_type', event.target.value)}><option value="offering">Offering</option><option value="pkwt">PKWT</option></SelectInput></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.is_active} onChange={(event) => form.setData('is_active', event.target.checked)} /> Status aktif</label><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setOpen(false)}>Batal</Button><Button>Simpan</Button></div></form></Card></div>}</AuthenticatedLayout>;
}
