import { Head, Link } from '@inertiajs/react';
import CandidateLayout from '@/Layouts/CandidateLayout';
import { Badge, Button, Card, EmptyState, PageHeader } from '@/Components/shared/ui';
import { ApplicationItem, Candidate, formatDate } from '@/lib/recruitment';

export default function Dashboard({ candidate, summary, latestApplications }: { candidate: { data: Candidate }; summary: { active: number; processed: number; accepted: number }; latestApplications: { data: ApplicationItem[] } | ApplicationItem[] }): JSX.Element {
    const applications = Array.isArray(latestApplications) ? latestApplications : latestApplications.data;
    return <CandidateLayout><Head title="Dashboard Kandidat" /><PageHeader title={`Halo, ${candidate.data.name}`} description="Pantau status lamaran dan lengkapi profil Anda." />{!candidate.data.has_cv && <div className="mb-6 rounded-lg border border-blue-200 bg-blue-50 p-4 text-blue-800"><strong>Lengkapi profil Anda</strong> — upload CV untuk bisa melamar.</div>}<div className="grid gap-4 md:grid-cols-3">{[['Lamaran Aktif', summary.active], ['Lamaran Diproses', summary.processed], ['Diterima', summary.accepted]].map(([label, value]) => <Card key={label} className="p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></Card>)}</div><Card className="mt-6 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-semibold">Lamaran Terbaru</h2><Link href="/candidate/applications"><Button type="button" variant="secondary">Lihat Semua Lamaran</Button></Link></div>{applications.length === 0 ? <EmptyState title="Belum ada lamaran" description="Mulai cari lowongan dan kirim lamaran pertama Anda." /> : <div className="divide-y">{applications.map((application) => <div key={application.id} className="flex items-center justify-between gap-4 py-3"><div><p className="font-medium">{application.job_posting?.position_name}</p><p className="text-sm text-slate-500">{formatDate(application.created_at)}</p></div><Badge tone="blue">{application.status_label ?? 'Lamaran Sedang Diproses'}</Badge></div>)}</div>}</Card></CandidateLayout>;
}
