import { Badge, Button, Card, FormLabel, PageHeader, TextInput } from '@/Components/shared/ui';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import { Head, router, useForm } from '@inertiajs/react';
import { FormEvent, useState } from 'react';

interface Graph { id: number; tenant_id: string; client_id: string; calendar_user_email: string; recruitment_mailbox?: string | null; is_active: boolean }

export default function GraphApi({ graphApiConfigs }: { graphApiConfigs: Graph[] }): JSX.Element {
    const current = graphApiConfigs[0];
    const [result, setResult] = useState('');
    const form = useForm({ tenant_id: current?.tenant_id ?? '', client_id: current?.client_id ?? '', client_secret: '', calendar_user_email: current?.calendar_user_email ?? '', recruitment_mailbox: current?.recruitment_mailbox ?? '', is_active: current?.is_active ?? true });
    function submit(event: FormEvent): void { event.preventDefault(); current ? router.put(`/admin/graph-api-configs/${current.id}`, form.data, {}) : router.post('/admin/graph-api-configs', form.data, {}); }
    function test(): void { if (!current) { setResult('Simpan konfigurasi dulu sebelum test koneksi.'); return; } router.post(`/admin/graph-api-configs/${current.id}/test-connection`, {}, { onSuccess: () => setResult('Test koneksi berhasil.'), onError: () => setResult('Test koneksi gagal.') }); }
    return <AuthenticatedLayout header={<h1 className="text-lg font-semibold">Microsoft Graph API</h1>}><Head title="Graph API" /><PageHeader title="Microsoft Graph API" description="Konfigurasi mailbox dan calendar recruitment." /><Card className="p-6"><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><div><FormLabel>Tenant ID</FormLabel><TextInput value={form.data.tenant_id} onChange={(e) => form.setData('tenant_id', e.target.value)} /></div><div><FormLabel>Client ID</FormLabel><TextInput value={form.data.client_id} onChange={(e) => form.setData('client_id', e.target.value)} /></div><div><FormLabel>Client Secret</FormLabel><TextInput type="password" value={form.data.client_secret} onChange={(e) => form.setData('client_secret', e.target.value)} placeholder="Masked" /></div><div><FormLabel>Calendar User Email</FormLabel><TextInput value={form.data.calendar_user_email} onChange={(e) => form.setData('calendar_user_email', e.target.value)} /></div><div><FormLabel>Recruitment Mailbox Email</FormLabel><TextInput value={form.data.recruitment_mailbox} onChange={(e) => form.setData('recruitment_mailbox', e.target.value)} /></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.data.is_active} onChange={(e) => form.setData('is_active', e.target.checked)} /> Status aktif</label><div className="flex justify-end gap-2 md:col-span-2"><Button type="button" variant="secondary" onClick={test}>Test Koneksi</Button><Button disabled={form.processing}>{form.processing ? 'Menyimpan...' : 'Simpan'}</Button></div>{result && <div className="md:col-span-2"><Badge tone={result.includes('berhasil') ? 'green' : 'red'}>{result}</Badge></div>}</form></Card></AuthenticatedLayout>;
}
